### ISSUE TITLE
Missing error handler on `socket`. TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by helmi-haddad** [Killians06/Angular-ledcontroller#3]
MTypeError: Cannot read property 'on' of undefined
    at Socket.<anonymous> (/home/helmi/Angular-ledcontroller/server.js:93:21)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at Socket.onevent (/home/helmi/Angular-ledcontroller/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/helmi/Angular-ledcontroller/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/helmi/Angular-ledcontroller/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/helmi/Angular-ledcontroller/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/helmi/Angular-ledcontroller/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/helmi/Angular-ledcontroller/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:77:13)

**Comment by Killians06** [comment]
You've got an arduino correctly Linked at your computer?
